variables:
  CONTAINER_BUILT_TAG: "rest-server:latest"
  CONTAINER_NAME: "rest-server"


stages:
- build
- deploy


cache:
  untracked: true
build:
  
  stage: build
  tags:
    - docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - env | grep 'PROD_ENV_' | sed -e 's/PROD_ENV_//g' >> .env
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE


test-deploy:
  stage: deploy
  tags:
    - docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker rmi $CONTAINER_BUILT_TAG || true
    - docker tag $CI_REGISTRY_IMAGE $CONTAINER_BUILT_TAG
    - env | grep 'PROD_ENV_' | sed -e 's/PROD_ENV_//g' >> .env
    - docker run -d --restart always --network litgame --env-file .env --name $CONTAINER_NAME -p 8042:8042 $CONTAINER_BUILT_TAG
